name: Update GitHub Profile

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours (midnight & noon UTC)
  workflow_dispatch:  # Allows manual run

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update GitHub Profile Readme
        run: |
          git config --global user.name "MeetOwaisAhmed"
          git config --global user.email "meetowaisahmed@gmail.com"
          git pull origin main
          date > last-updated.txt
          git add last-updated.txt
          git commit -m "Updated profile automatically on $(date)" || echo "No changes to commit"
          git push origin main
