name: Update GitHub Profile

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours (at midnight & noon UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v18
        with:
          node-version: 18

      - name: Update GitHub Profile Readme
        run: |
          git config --global user.name "MeetOwaisAhmed"
          git config --global user.email "meetowaisahmed@gmail.com"
          git pull origin main
          date > last-updated.txt
          git add last-updated.txt
          git commit -m "Updated profile automatically on $(date)" || echo "No changes to commit"
          git push origin main

      - name: Update Contribution Graph (GitHub Profile Summary)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_repositories: yes
          plugin_stars: yes
          plugin_habits: yes
          plugin_notable: yes
